# Generated by Django 5.1 on 2024-09-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=89, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lname',
            field=models.CharField(max_length=88, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Username',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pass1',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pass2',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
