# Generated by Django 5.1 on 2024-09-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_student_phone_student_fname_student_lname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, null='True')),
                ('phone', models.CharField(max_length=10, null='True')),
                ('desc', models.TextField(null='True')),
                ('var', models.TextField(null='True')),
                ('var2', models.TextField(null='True')),
            ],
        ),
    ]
